### PR TITLE
Feature/simgan support/symbolic regression

### PR DESCRIPTION
**Pull request by gabriel-q-wang**
Described in Issue #265

### CODE REVIEW

**Comment by gabriel-q-wang** [comment]
Note this ends up being a fairly large change, as I added a bunch of new parameters, changed the training loop to always use all the options, etc. I wouldn't merge this immediately, I would look carefully and test it more to make sure its what we want to do

**Comment by gabriel-q-wang** [comment]
Wait still getting some GPU issues, gonna close for now

**Comment by gabriel-q-wang** [comment]
Fixed issues, should be good now. Main thing is that it now forces/assumes you're running on GPU. If you want to run on CPU you'll have to manually change some "device=" sections of the code

**Comment by roddtalebi** [comment]
need to roll back some commits to remove the 'dynamic' stuff and hopefully that'll fix the device issue

**Pull request closed without merging**
